version: '3.8'
services:
  runner:
    container_name: gha_runner
    image: &image gha_runner:latest
    restart: always
    volumes: &volumes
      - ./exec-runner.sh:/actions-runner/exec-runner.sh
    env_file:
      - env.sh
    command: &command /actions-runner/exec-runner.sh
    logging: &logging
      driver: 'json-file'
      options:
        max-size: 1M
        max-file: '3'
